import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <head>
      <link href="https://fonts.cdnfonts.com/css/ostrich-sans-2" rel="stylesheet"/>
      <link href="https://fonts.cdnfonts.com/css/black-witcher-personal-use" rel="stylesheet" />
                
      <link href="https://fonts.cdnfonts.com/css/walrus" rel="stylesheet" />
      </head>
      <body className={inter.className}>
      <div id="modal-root"></div>
        {children}
        </body>
    </html>
  )
}
